import './styles.css';
import './homeFeatures.css';
import './mobileUxFixes.css';
import './editorialUi.css';
import { registerGlobalErrorLogging } from './debug/debugLog';
import { StudyApplication } from './app/application';
const root = document.querySelector<HTMLElement>('#app');
if (!root) throw new Error('Missing #app root.');
registerGlobalErrorLogging();
new StudyApplication(root).start();
